<!DOCTYPE html><html lang='en'><head><title>[except.uncaught]</title><meta charset='UTF-8'><link rel='stylesheet' type='text/css' href='14882.css'><link rel='stylesheet' type='text/css' href='https://fonts.googleapis.com/css2?family=Noto+Serif'><link rel='stylesheet' type='text/css' href='https://fonts.googleapis.com/css2?family=Noto+Sans'><link rel='stylesheet' type='text/css' href='https://fonts.googleapis.com/css2?family=Noto+Sans+Mono'><link rel='icon' href='icon.png'><link rel='stylesheet' type='text/css' href='expanded.css' title='Normal'><link rel='alternate stylesheet' type='text/css' href='colored.css' title='Notes and examples colored'><link rel='alternate stylesheet' type='text/css' href='normative-only.css' title='Notes and examples hidden'></head><body><div class='wrapper'><h1 ><a class='secnum' style='min-width:50pt'>14</a> Exception handling <a class='abbr_ref' href='./#except'>[except]</a></h1><h2 ><a class='secnum' style='min-width:65pt'>14.6</a> Special functions <a class='abbr_ref' href='except.special#except.uncaught'>[except.special]</a></h2><h3 ><a class='secnum' style='min-width:80pt'>14.6.3</a> The <span class='texttt'>std&#x200b;::&#x200b;uncaught_<span class='shy'></span>exceptions</span> function <a class='abbr_ref'>[except.uncaught]</a></h3><div class='texpara'><a class='index' id='lib:uncaught_exceptions'></a></div><div class='para' id='1'><div class='marginalizedparent'><a class='marginalized' href='#1'>1</a></div><div class='sourceLinkParent'><a class='sourceLink' href='https://github.com/cplusplus/draft/tree/896196c8c08ed834ef876c29c1182510da9c1a1c/source/exceptions.tex#L1129'>#</a></div><div class='texpara'><div id='1.sentence-1' class='sentence'>An exception is considered uncaught
after completing the initialization of the <a href='except.throw#def:exception_handling,exception_object' title='14.2&emsp;Throwing an exception&emsp;[except.throw]'>exception object</a>
until completing the activation of a handler for the exception (<a href='except.handle' title='14.4&emsp;Handling an exception'>[except.<span class='shy'></span>handle]</a>)<a class='hidden_link' href='#1.sentence-1'>.</a></div> <div id='note-1' class='note'><div class='texpara'>[<i>Note&nbsp;<a href='#note-1'>1</a></i>:&ensp;<div id='1.sentence-2' class='sentence'>As a consequence, an exception is considered uncaught
during any stack unwinding resulting from it being thrown<a class='hidden_link' href='#1.sentence-2'>.</a></div> â€”&nbsp;<i>end note</i>]</div></div> <div id='1.sentence-3' class='sentence'>
If an exception is rethrown (<a href='expr.throw' title='7.6.18&emsp;Throwing an exception'>[expr.<span class='shy'></span>throw]</a>, <a href='propagation' title='17.9.7&emsp;Exception propagation'>[propagation]</a>),
it is considered uncaught from the point of rethrow
until the rethrown exception is caught<a class='hidden_link' href='#1.sentence-3'>.</a></div> <div id='1.sentence-4' class='sentence'>The function <span class='texttt'>std<span class='operator'>&#x200b;::&#x200b;</span>uncaught_<span class='shy'></span>exceptions</span> (<a href='uncaught.exceptions' title='17.9.6&emsp;uncaught_&shy;exceptions'>[uncaught.<span class='shy'></span>exceptions]</a>)
returns the number of uncaught exceptions in the current thread<a class='hidden_link' href='#1.sentence-4'>.</a></div> </div></div></div></body></html>