<!DOCTYPE html><html lang='en'><head><title>[except.terminate]</title><meta charset='UTF-8'/><link rel='stylesheet' type='text/css' href='14882.css'/><link rel='stylesheet' type='text/css' href='https://fonts.googleapis.com/css2?family=Noto+Serif'/><link rel='stylesheet' type='text/css' href='https://fonts.googleapis.com/css2?family=Noto+Sans'/><link rel='stylesheet' type='text/css' href='https://fonts.googleapis.com/css2?family=Noto+Sans+Mono'/><link rel='icon' href='icon.png'/><link rel='stylesheet' type='text/css' href='expanded.css' title='Normal'/><link rel='alternate stylesheet' type='text/css' href='colored.css' title='Notes and examples colored'/><link rel='alternate stylesheet' type='text/css' href='normative-only.css' title='Notes and examples hidden'/></head><body><div class='wrapper'><h1 ><a class='secnum' style='min-width:50pt'>14</a> Exception handling <a class='abbr_ref' href='./#except'>[except]</a></h1><h2 ><a class='secnum' style='min-width:65pt'>14.6</a> Special functions <a class='abbr_ref' href='except.special#except.terminate'>[except.special]</a></h2><h3 ><a class='secnum' style='min-width:80pt'>14.6.2</a> The <span class='texttt'>std&#x200b;::&#x200b;terminate</span> function <a class='abbr_ref'>[except.terminate]</a></h3><div class='para' id='1'><div class='marginalizedparent'><a class='marginalized' href='#1'>1</a></div><div class='sourceLinkParent'><a class='sourceLink' href='https://github.com/cplusplus/draft/tree/8410aac1b84ec161b6990441acde53185f958135/source/exceptions.tex#L1013'>#</a></div><div class='texpara'><div id='1.sentence-1' class='sentence'><a class='index' id=':terminate'></a>In some situations, exception handling is abandoned
for less subtle error handling techniques<a class='hidden_link' href='#1.sentence-1'>.</a></div> <div id='note-1' class='note'><div class='texpara'>[<i>Note&nbsp;<a href='#note-1'>1</a></i>:&ensp;<div id='1.sentence-2' class='sentence'>These situations are:
<a class='index' id=':terminate,called'></a><ul class='itemize'><li id='1.1'><div class='marginalizedparent' style='left:-27mm'><a class='marginalized' href='#1.1'>(1.1)</a></div>when the exception handling mechanism, after completing
the initialization of the exception object
but before
activation of a handler for the exception (<a href='except.throw' title='14.2&emsp;Throwing an exception'>[except.<span class='shy'></span>throw]</a>),
calls a function that exits
via an exception, or</li><li id='1.2'><div class='marginalizedparent' style='left:-27mm'><a class='marginalized' href='#1.2'>(1.2)</a></div>when the exception handling mechanism cannot find a handler for a thrown exception (<a href='except.handle' title='14.4&emsp;Handling an exception'>[except.<span class='shy'></span>handle]</a>), or</li><li id='1.3'><div class='marginalizedparent' style='left:-27mm'><a class='marginalized' href='#1.3'>(1.3)</a></div>when the search for a <a href='except.handle' title='14.4&emsp;Handling an exception&emsp;[except.handle]'>handler</a> encounters the
outermost block of a function
with a non-throwing <a href='except.spec' title='14.5&emsp;Exception specifications&emsp;[except.spec]'>exception specification</a>, or</li><li id='1.4'><div class='marginalizedparent' style='left:-27mm'><a class='marginalized' href='#1.4'>(1.4)</a></div>when the destruction of an object during <a href='except.ctor#def:stack_unwinding' title='14.3&emsp;Constructors and destructors&emsp;[except.ctor]'>stack unwinding</a>
terminates by throwing an exception, or</li><li id='1.5'><div class='marginalizedparent' style='left:-27mm'><a class='marginalized' href='#1.5'>(1.5)</a></div>when initialization of a non-block
variable with static or thread storage duration (<a href='basic.start.dynamic' title='6.9.3.3&emsp;Dynamic initialization of non-block variables'>[basic.<span class='shy'></span>start.<span class='shy'></span>dynamic]</a>)
exits via an exception, or</li><li id='1.6'><div class='marginalizedparent' style='left:-27mm'><a class='marginalized' href='#1.6'>(1.6)</a></div>when destruction of an object with static or thread storage duration exits
via an exception (<a href='basic.start.term' title='6.9.3.4&emsp;Termination'>[basic.<span class='shy'></span>start.<span class='shy'></span>term]</a>), or</li><li id='1.7'><div class='marginalizedparent' style='left:-27mm'><a class='marginalized' href='#1.7'>(1.7)</a></div>when execution of a function registered with
<span class='texttt'>std<span class='operator'>&#x200b;::&#x200b;</span>atexit</span> or <span class='texttt'>std<span class='operator'>&#x200b;::&#x200b;</span>at_<span class='shy'></span>quick_<span class='shy'></span>exit</span>
exits via an exception (<a href='support.start.term' title='17.5&emsp;Startup and termination'>[support.<span class='shy'></span>start.<span class='shy'></span>term]</a>), or</li><li id='1.8'><div class='marginalizedparent' style='left:-27mm'><a class='marginalized' href='#1.8'>(1.8)</a></div>when a
<a href='expr.throw#nt:throw-expression' title='7.6.18&emsp;Throwing an exception&emsp;[expr.throw]'><span id='ntref:throw-expression'><span class='textsf'><i >throw-expression</i></span></span></a> (<a href='expr.throw' title='7.6.18&emsp;Throwing an exception'>[expr.<span class='shy'></span>throw]</a>)
with no operand attempts to rethrow an exception and no exception is being
handled (<a href='except.throw' title='14.2&emsp;Throwing an exception'>[except.<span class='shy'></span>throw]</a>), or</li><li id='1.9'><div class='marginalizedparent' style='left:-27mm'><a class='marginalized' href='#1.9'>(1.9)</a></div>when the function <span class='texttt'>std<span class='operator'>&#x200b;::&#x200b;</span>nested_<span class='shy'></span>exception<span class='operator'>&#x200b;::&#x200b;</span>rethrow_<span class='shy'></span>nested</span> is called for an object
that has captured no exception (<a href='except.nested' title='17.9.8&emsp;nested_&shy;exception'>[except.<span class='shy'></span>nested]</a>), or</li><li id='1.10'><div class='marginalizedparent' style='left:-27mm'><a class='marginalized' href='#1.10'>(1.10)</a></div>when execution of the initial function of a thread exits via
an exception (<a href='thread.thread.constr' title='33.4.3.3&emsp;Constructors'>[thread.<span class='shy'></span>thread.<span class='shy'></span>constr]</a>), or</li><li id='1.11'><div class='marginalizedparent' style='left:-27mm'><a class='marginalized' href='#1.11'>(1.11)</a></div>for a parallel algorithm whose <span class='texttt'>ExecutionPolicy</span> specifies such
behavior (<a href='execpol.seq' title='22.12.4&emsp;Sequenced execution policy'>[execpol.<span class='shy'></span>seq]</a>, <a href='execpol.par' title='22.12.5&emsp;Parallel execution policy'>[execpol.<span class='shy'></span>par]</a>, <a href='execpol.parunseq' title='22.12.6&emsp;Parallel and unsequenced execution policy'>[execpol.<span class='shy'></span>parunseq]</a>),
when execution of an element access function (<a href='algorithms.parallel.defns' title='27.3.1&emsp;Preamble'>[algorithms.<span class='shy'></span>parallel.<span class='shy'></span>defns]</a>)
of the parallel algorithm exits via an exception (<a href='algorithms.parallel.exceptions' title='27.3.4&emsp;Parallel algorithm exceptions'>[algorithms.<span class='shy'></span>parallel.<span class='shy'></span>exceptions]</a>), or</li><li id='1.12'><div class='marginalizedparent' style='left:-27mm'><a class='marginalized' href='#1.12'>(1.12)</a></div>when the destructor or the move assignment operator is invoked on an object
of type <span class='texttt'>std<span class='operator'>&#x200b;::&#x200b;</span>thread</span> that refers to
a joinable thread (<a href='thread.thread.destr' title='33.4.3.4&emsp;Destructor'>[thread.<span class='shy'></span>thread.<span class='shy'></span>destr]</a>, <a href='thread.thread.assign' title='33.4.3.5&emsp;Assignment'>[thread.<span class='shy'></span>thread.<span class='shy'></span>assign]</a>), or</li><li id='1.13'><div class='marginalizedparent' style='left:-27mm'><a class='marginalized' href='#1.13'>(1.13)</a></div>when a call to a <span class='texttt'>wait<span class='parenthesis'>(</span><span class='parenthesis'>)</span></span>, <span class='texttt'>wait_<span class='shy'></span>until<span class='parenthesis'>(</span><span class='parenthesis'>)</span></span>, or <span class='texttt'>wait_<span class='shy'></span>for<span class='parenthesis'>(</span><span class='parenthesis'>)</span></span>
function on a condition variable (<a href='thread.condition.condvar' title='33.7.4&emsp;Class condition_&shy;variable'>[thread.<span class='shy'></span>condition.<span class='shy'></span>condvar]</a>, <a href='thread.condition.condvarany' title='33.7.5&emsp;Class condition_&shy;variable_&shy;any'>[thread.<span class='shy'></span>condition.<span class='shy'></span>condvarany]</a>)
fails to meet a postcondition<a class='hidden_link' href='#1.sentence-2'>.</a></li></ul></div> â€”&nbsp;<i>end note</i>]</div></div></div></div><div class='para' id='2'><div class='marginalizedparent'><a class='marginalized' href='#2'>2</a></div><div class='sourceLinkParent'><a class='sourceLink' href='https://github.com/cplusplus/draft/tree/8410aac1b84ec161b6990441acde53185f958135/source/exceptions.tex#L1087'>#</a></div><div class='texpara'><div id='2.sentence-1' class='sentence'><a class='index' id=':terminate_'></a>In such cases,
the function <span class='texttt'>std<span class='operator'>&#x200b;::&#x200b;</span>terminate</span> is invoked (<a href='exception.terminate' title='17.9.5&emsp;Abnormal termination'>[exception.<span class='shy'></span>terminate]</a>)<a class='hidden_link' href='#2.sentence-1'>.</a></div> <div id='2.sentence-2' class='sentence'>In the situation where no matching handler is found, it is
<a class='index' id=':stack_unwinding_before_invocation_of_std::terminate'></a>implementation-defined
whether or not the stack is unwound
before <span class='texttt'>std<span class='operator'>&#x200b;::&#x200b;</span>terminate</span> is invoked<a class='hidden_link' href='#2.sentence-2'>.</a></div> <div id='2.sentence-3' class='sentence'>In the situation where the search for a handler (<a href='except.handle' title='14.4&emsp;Handling an exception'>[except.<span class='shy'></span>handle]</a>) encounters the
outermost block of a function
with a non-throwing exception specification (<a href='except.spec' title='14.5&emsp;Exception specifications'>[except.<span class='shy'></span>spec]</a>), it is
<a class='index' id=':whether_stack_is_unwound_before_invoking_the_function_std::terminate_when_a_noexcept_specification_is_violated'></a>implementation-defined
whether the stack is unwound, unwound partially, or not unwound at all
before the function <span class='texttt'>std<span class='operator'>&#x200b;::&#x200b;</span>terminate</span> is invoked<a class='hidden_link' href='#2.sentence-3'>.</a></div> <div id='2.sentence-4' class='sentence'>In all other situations, the stack shall not be unwound before
the function <span class='texttt'>std<span class='operator'>&#x200b;::&#x200b;</span>terminate</span>
is invoked<a class='hidden_link' href='#2.sentence-4'>.</a></div> <div id='2.sentence-5' class='sentence'>An implementation is not permitted to finish stack unwinding
prematurely based on a determination that the unwind process
will eventually cause an invocation of the function
<span class='texttt'>std<span class='operator'>&#x200b;::&#x200b;</span>terminate</span><a class='hidden_link' href='#2.sentence-5'>.</a></div></div></div></div></body></html>